#!/usr/bin/env bash
#
#
VERSION="1.0.1"
sudo rm -f /usr/local/bin/hampi-backup-restore.sh
sudo cp nexus-backup-restore/nexus-backup-restore.sh /usr/local/bin/
sudo rm -f /usr/local/share/applications/hampi-backup-restore.desktop
sudo cp nexus-backup-restore/nexus-backup-restore.desktop /usr/local/share/applications/
[ -f $HOME/.local/share/applications/hampi-backup-restore.desktop ] && rm -f $HOME/.local/share/applications/hampi-backup-restore.desktop
